
package edu.bath.soak.ws.dhcp;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Windows DHCP Service Interface
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DHCPWSvc", targetNamespace = "http://www.bath.edu/soak/ws/dhcp/0.3", wsdlLocation = "file:/home/occ/workspace/soakspring/src/wsdl/DHCPWsvc.wsdl")
public class DHCPWSvc
    extends Service
{

    private final static URL DHCPWSVC_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.bath.soak.ws.dhcp.DHCPWSvc.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.bath.soak.ws.dhcp.DHCPWSvc.class.getResource(".");
            url = new URL(baseUrl, "file:/home/occ/workspace/soakspring/src/wsdl/DHCPWsvc.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/occ/workspace/soakspring/src/wsdl/DHCPWsvc.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DHCPWSVC_WSDL_LOCATION = url;
    }

    public DHCPWSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DHCPWSvc() {
        super(DHCPWSVC_WSDL_LOCATION, new QName("http://www.bath.edu/soak/ws/dhcp/0.3", "DHCPWSvc"));
    }

    /**
     * 
     * @return
     *     returns DHCPWSvcSoap
     */
    @WebEndpoint(name = "DHCPWSvcSoap")
    public DHCPWSvcSoap getDHCPWSvcSoap() {
        return super.getPort(new QName("http://www.bath.edu/soak/ws/dhcp/0.3", "DHCPWSvcSoap"), DHCPWSvcSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DHCPWSvcSoap
     */
    @WebEndpoint(name = "DHCPWSvcSoap")
    public DHCPWSvcSoap getDHCPWSvcSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bath.edu/soak/ws/dhcp/0.3", "DHCPWSvcSoap"), DHCPWSvcSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns DHCPWSvcSoap
     */
    @WebEndpoint(name = "DHCPWSvcSoap12")
    public DHCPWSvcSoap getDHCPWSvcSoap12() {
        return super.getPort(new QName("http://www.bath.edu/soak/ws/dhcp/0.3", "DHCPWSvcSoap12"), DHCPWSvcSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DHCPWSvcSoap
     */
    @WebEndpoint(name = "DHCPWSvcSoap12")
    public DHCPWSvcSoap getDHCPWSvcSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bath.edu/soak/ws/dhcp/0.3", "DHCPWSvcSoap12"), DHCPWSvcSoap.class, features);
    }

}
